# Generated by Django 6.0 on 2026-01-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflows',
            new_name='Inflow',
        ),
    ]
